### ISSUE TITLE
Strange files appear in the repository

### ISSUE THREAD

**Issue by genggng** [xiaofulenlong/Nerf#1]
As shown below, there are a lot of redundant files likes _.DS_Store_ for Macos out there, which should be avoided from being uploaded. I think you should write a .gitignore to filter these files.

<img width="979" alt="image" src="https://github.com/xiaofulenlong/Nerf/assets/47470904/9442e481-f95a-4ee0-97e7-f318a5f38af5">

**Comment by xiaofulenlong** [comment]
Very constructive comments，Thanks!
